---
# Source: nodeserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "nodeserver-service"
  labels:
    chart: "nodeserver-1.0.0"
spec:
  type: NodePort
  ports:
  - name: http  
    port: 3000
  selector:
    app: "nodeserver-selector"
---
# Source: nodeserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nodeserver-deployment"
  labels:
    chart: 'nodeserver-1.0.0'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "nodeserver-selector"
      version: "current"
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: "nodeserver-selector"
        version: "current"
    spec:
      containers:
      - name: "nodeserver"
        image: "nodeserver:1.0.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value : "3000"
